#include<stdio.h>
int main()
{
    int i,j,k=0,a[100],n,c,d=0;
    scanf("%d",&n);
    for(i=2;i<=n;i++)
    {
        c=0;
        for(j=2;j<i;j++)
        {
            if(i%j==0)
            {
                c=1;
                break;
            }
        }
        if(c==0)
        {
            a[k]=i;
            k++;
        }
    }
    for(i=0;i<k;i++)
    {
        for(j=0;j<k;j++)
        {
            if(a[i]*a[j]==n)
            {
                printf("%d %d",a[i],a[j]);
                d=1;
                break;
            }
        }
        if(d==1)
        {
            break;
        }
    }
    if(d==0)
    printf("-1");
}